#!/usr/bin/env python3
"""
Export YouTube cookies from browser to cookies.txt for yt-dlp
Supports Chrome, Firefox, Edge browsers
"""

import sys
import json
import sqlite3
import shutil
from pathlib import Path
from datetime import datetime

def get_chrome_cookies():
    """Extract cookies from Chrome browser"""
    chrome_path = Path.home() / "AppData" / "Local" / "Google" / "Chrome" / "User Data" / "Default" / "Cookies"

    if not chrome_path.exists():
        return None

    try:
        # Copy to temp location since Chrome locks the DB
        import tempfile
        with tempfile.NamedTemporaryFile(delete=False, suffix='.db') as tmp:
            shutil.copyfile(chrome_path, tmp.name)
            tmp_path = tmp.name

        conn = sqlite3.connect(tmp_path)
        cursor = conn.cursor()

        # Get YouTube and related cookies
        cursor.execute("""
            SELECT host_key, path, is_secure, expires_utc, name, value
            FROM cookies
            WHERE host_key LIKE '%youtube%' OR host_key LIKE '%google%'
            ORDER BY host_key, name
        """)

        cookies = cursor.fetchall()
        conn.close()

        import os
        os.unlink(tmp_path)

        return cookies
    except Exception as e:
        print(f"[ERROR] Failed to read Chrome cookies: {e}")
        return None

def get_firefox_cookies():
    """Extract cookies from Firefox browser"""
    firefox_path = Path.home() / "AppData" / "Roaming" / "Mozilla" / "Firefox"

    if not firefox_path.exists():
        return None

    try:
        # Find the profile directory
        profiles = list(firefox_path.glob("Profiles/*/cookies.sqlite"))
        if not profiles:
            return None

        cookies_db = profiles[0]

        import tempfile
        with tempfile.NamedTemporaryFile(delete=False, suffix='.db') as tmp:
            shutil.copyfile(cookies_db, tmp.name)
            tmp_path = tmp.name

        conn = sqlite3.connect(tmp_path)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT host, path, isSecure, expiry, name, value
            FROM moz_cookies
            WHERE host LIKE '%youtube%' OR host LIKE '%google%'
            ORDER BY host, name
        """)

        cookies = cursor.fetchall()
        conn.close()

        import os
        os.unlink(tmp_path)

        return cookies
    except Exception as e:
        print(f"[ERROR] Failed to read Firefox cookies: {e}")
        return None

def save_netscape_format(cookies, filename):
    """Save cookies in Netscape/curl format for yt-dlp"""
    if not cookies:
        return False

    with open(filename, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by export_youtube_cookies.py\n")
        f.write(f"# {datetime.now().isoformat()}\n\n")

        for cookie in cookies:
            if len(cookie) == 6:
                host, path, is_secure, expires, name, value = cookie
            else:
                continue

            # Convert expires from microseconds to seconds
            if expires > 1000000000000000:  # Microseconds
                expires = expires // 1000000

            secure = "TRUE" if is_secure else "FALSE"
            httponly = "TRUE"  # Most YouTube cookies are httponly

            line = f"{host}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
            f.write(line)

    return True

def main():
    print("[INFO] YouTube Cookie Exporter")
    print("=" * 50)

    # Try Chrome first
    print("\n[1/3] Checking Chrome browser...")
    chrome_cookies = get_chrome_cookies()
    if chrome_cookies:
        print(f"[OK] Found {len(chrome_cookies)} Chrome cookies")
        if save_netscape_format(chrome_cookies, "cookies.txt"):
            print("[OK] Saved to cookies.txt")
            print("\n[NEXT] Now run:")
            print("  python process_video.py --url 'https://www.youtube.com/watch?v=...' --language zh")
            return 0
    else:
        print("[SKIP] Chrome not found or no YouTube cookies")

    # Try Firefox
    print("\n[2/3] Checking Firefox browser...")
    firefox_cookies = get_firefox_cookies()
    if firefox_cookies:
        print(f"[OK] Found {len(firefox_cookies)} Firefox cookies")
        if save_netscape_format(firefox_cookies, "cookies.txt"):
            print("[OK] Saved to cookies.txt")
            return 0
    else:
        print("[SKIP] Firefox not found or no YouTube cookies")

    # If no cookies found
    print("\n[3/3] Cookie export options:")
    print("\n[OPTION A] Manual Cookie Export (Recommended)")
    print("  1. Open YouTube in your browser (already logged in)")
    print("  2. Press F12 to open Developer Tools")
    print("  3. Go to Application → Storage → Cookies → https://www.youtube.com")
    print("  4. Right-click on a cookie and select 'Export all Cookies'")
    print("  5. Save as 'cookies.txt' in this directory")
    print("\n[OPTION B] Use Local Video File")
    print("  If you have the video file downloaded locally, use:")
    print("  python process_video.py --local-video '/path/to/video.mp4' ...")
    print("\n[OPTION C] Install Browser Cookie Extension")
    print("  Chrome: 'Get cookies.txt' extension")
    print("  Firefox: 'Export Cookies' extension")

    return 1

if __name__ == "__main__":
    sys.exit(main())
